<%@ Page Title="Address Book" MasterPageFile="MasterPage.master" Language="C#" AutoEventWireup="true" CodeFile="addressBook.aspx.cs" Inherits="addressBook" %>

<asp:Content ID="addressBookContent" ContentPlaceHolderID="ContentPlaceHolder1" runat="server">

    <h1>Address Book using GridView</h1>

<asp:GridView AutoGenerateColumns="False" CssClass="addressGridView" id="grid" runat="server" BackColor="LightGoldenrodYellow" BorderColor="Tan" BorderWidth="1px" CellPadding="2" ForeColor="Black" GridLines="None" OnSelectedIndexChanged="grid_SelectedIndexChanged" OnSelectedIndexChanging="grid_SelectedIndexChanging" OnRowCancelingEdit="grid_RowCancelingEdit" OnRowEditing="grid_RowEditing" >
    <AlternatingRowStyle BackColor="PaleGoldenrod" />
    <Columns>
        <asp:BoundField DataField="CookName" HeaderText="Name" />
        <asp:HyperLinkField DataTextField="CookEmail" NavigateUrl="search.aspx" HeaderText="eMail" />
        <%--No code for asp:ButtonField's action, it's secretly done by this ctrl. Clicking this btm fires "SelectedIndexChanged" made by doubleClick on grid--%>
        <asp:ButtonField CommandName="Select" HeaderText="ButtonField" ShowHeader="True" Text="Select This Row" />
        
        <asp:CommandField ShowEditButton="True" HeaderText="cmdFld.ShowEditBtn" />
        <asp:CommandField SelectText="same fn as BtnFld" ShowSelectButton="True" HeaderText="cmdFld.SelectTxt" />



    </Columns>
    <%--Following styles AutoGenerated: in design mode select grid, click SmartTab, Auto Format, choose from available styles--%>
    <FooterStyle BackColor="Tan" />
    <HeaderStyle BackColor="Tan" Font-Bold="True" />
    <PagerStyle BackColor="PaleGoldenrod" ForeColor="DarkSlateBlue" HorizontalAlign="Center" />
    <SelectedRowStyle BackColor="DarkSlateBlue" ForeColor="GhostWhite" />
    <SortedAscendingCellStyle BackColor="#FAFAE7" />
    <SortedAscendingHeaderStyle BackColor="#DAC09E" />
    <SortedDescendingCellStyle BackColor="#E1DB9C" />
    <SortedDescendingHeaderStyle BackColor="#C2A47B" />

</asp:GridView>
   
    <br /><asp:Label ID="gridLbl" runat="server" Text=""></asp:Label>

<%--==========DetailsView to display details of ONE record in rows instead of columns as in GridView========--%>
<%--==========DetailsView to display details of ONE record in rows instead of columns as in GridView========--%>
<%--==========DetailsView to display details of ONE record in rows instead of columns as in GridView========--%>
    <asp:DetailsView AutoGenerateRows="False" ID="DetailsView1" runat="server" Height="50px" Width="125px" OnModeChanging="DetailsView1_ModeChanging">
        <fields>
<%--            <asp:BoundField DataField="cookName" HeaderText="Name" />--%>
            <asp:BoundField DataField="cookAddress" HeaderText="Add" />
            <asp:BoundField DataField="cookPhone" HeaderText="Ph" />

<%--a BoundField converted to TemplateField as ...smartTag..EditField..ConvertToTemplate..(so we can customize looks when this field enters EDIT/INSERT modes etc)--%>
            <asp:TemplateField HeaderText="eMail">
                <EditItemTemplate>
                    <asp:TextBox ID="editEmailTxtBox" runat="server" Text='<%# Bind("cookEmail") %>'></asp:TextBox>
                </EditItemTemplate>
                <InsertItemTemplate>
                    <asp:TextBox ID="insertEmailTxtBox" runat="server" Text='<%# Bind("cookEmail") %>'></asp:TextBox>
                </InsertItemTemplate>
                <ItemTemplate>
                    <asp:Label ID="emailLbl" runat="server" Text='<%# Bind("cookEmail") %>'></asp:Label>
                </ItemTemplate>
            </asp:TemplateField>

   <%--smartTag..NewField..CommandField..check the EDIT box..Then boltOfLight..doubleClick ModeChangING to create handler for EDIT/CNACEL. while for UPDATE u need another handler updatING...--%>
            <asp:CommandField ShowEditButton="True" />
        </fields>

        <HeaderTemplate>
            <%# "Name: " + Eval("cookName") %>
        </HeaderTemplate>

    </asp:DetailsView>
    <asp:Label id="focusHereWhenGridViewRowSelected" runat="server" />
</asp:Content>
